---

x-common-keys: &common-keys
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - arr_network

services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8081:8080"   # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - arr_network

  qbittorrent:
    <<: *common-keys
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent.internal
    environment:
      - LIBTORRENT=v1
      # VPN
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_AUTO_PORT_FORWARD=false
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ${ROOT_DIR}/torrents:/data:rw
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.home.arpa`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080

  jellyfin:
    <<: *common-keys
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.home.arpa #optional
    volumes:
      - jellyfin:/config
      - ${ROOT_DIR}/media/tv:/data/tvshows
      - ${ROOT_DIR}/media/movies:/data/movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.home.arpa`)
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  radarr:
  sonarr:
  prowlarr:
  jellyfin:

networks:
  default:
    name: arr_network
