---

x-common-keys: &common-keys
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - arr_network

services:

  traefik:
    <<: *common-keys
    image: traefik:v3.6
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/dynamic/tls.yaml"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=arr_network"

      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.home.arpa`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic:/dynamic:ro


  qbittorrent:
    <<: *common-keys
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - LIBTORRENT=v1
      # VPN
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_AUTO_PORT_FORWARD=false
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ${ROOT_DIR}/torrents:/data:rw
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.home.arpa`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080

  jellyfin:
    <<: *common-keys
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.home.arpa #optional
    volumes:
      - jellyfin:/config
      - ${ROOT_DIR}/media/tv:/data/tvshows
      - ${ROOT_DIR}/media/movies:/data/movies
    ports:
      - 7359:7359/udp
      - "8096:8096"
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.home.arpa`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - prowlarr:/config
    env_file: ./prowlarr/config.env
    environment:
      - PROWLARR__AUTH__APIKEY_FILE=/run/secrets/prowlarr_api_key
    secrets:
      - prowlarr_api_key
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.arpa`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

  radarr:
    <<: *common-keys
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarr:/config
      - ${ROOT_DIR}/media/movies:/movies
    env_file: ./radarr/config.env
    environment:
      - RADARR__AUTH__APIKEY_FILE=/run/secrets/radarr_api_key
    secrets:
      - radarr_api_key
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.home.arpa`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878

secrets:
  radarr_api_key:
    file: ./radarr/secrets/api-key.secret
  prowlarr_api_key:
    file: ./prowlarr/secrets/api-key.secret

volumes:
  radarr:
  sonarr:
  prowlarr:
  jellyfin:

networks:
  arr_network:
    name: arr_network
